### ISSUE TITLE
Not working due to Read Proces Memory

### ISSUE THREAD

**Issue by SaitamaRules** [FssAy/bear100#4]
As of today and following the instructions for singleplayer mode is not working due to 0x12B. I guess its due to an update that changed several adresses. Will it be fixed?

**Comment by FssAy** [comment]
Indeed, the offsets are outdated. It's an easy fix anyone can do by changing the config file, but I will update it as soon as I am able to download the update. Thanks for the notification.

**Comment by SaitamaRules** [comment]
I am sorry, I just know zero about this topic..
Anyways, thank you for your work, its apreciated!!

**Comment by CenkCamkiran** [comment]
> Indeed, the offsets are outdated. It's an easy fix anyone can do by changing the config file, but I will update it as soon as I am able to download the update. Thanks for the notification.

Hello there. Thanks for your work. I am software engineer and i want to learn the concepts of this software. How do you find offsets, using some tools or algorithm? Could you help me sir?

**Comment by FssAy** [comment]
> I am sorry, I just know zero about this topic.. Anyways, thank you for your work, its apreciated!!

Fixed in the newest [commit](https://github.com/DmitrijVC/bear100/commit/ca2bd58ab0a59e3ac35d6ea4583b11f4f7f9f2a2).
No need to download the executable, just update your config with the one found in the [README](https://github.com/DmitrijVC/bear100#config).

**Comment by FssAy** [comment]
> > Indeed, the offsets are outdated. It's an easy fix anyone can do by changing the config file, but I will update it as soon as I am able to download the update. Thanks for the notification.
> 
> Hello there. Thanks for your work. I am software engineer and i want to learn the concepts of this software. How do you find offsets, using some tools or algorithm? Could you help me sir?

This is not the topic of this issue, contact me on Discord: FssAy#8648
