### ISSUE TITLE
Sort of anticheat...

### ISSUE THREAD

**Issue by ZekyTheWolf** [FssAy/bear100#5]
Looks like, they made some sort of anticheat, where when you use your mod, get that collectible it will make your view foggy, cant see anything and is played some sort of dialog in garage :D

**Comment by ZekyTheWolf** [comment]
* After reinstalling game and EA client, works fine and without any of those "anticheat" effects.

**Comment by FssAy** [comment]
It's unrelated. There was no game update and EA does not implement any anticheat systems to such games. What is more it's a literal clone of the NFS Heat (Proved with all the unused models and settings), so if they make money from sales and no microtransactions like GTA shark cards they do not care.
